# ---- Etapa 1: Construcción ----
    FROM node:20-alpine AS builder

    WORKDIR /app
    
    # Copiar archivos esenciales primero para aprovechar caché de Docker
    COPY package.json package-lock.json ./
    
    RUN npm install
    
    # Copiar todo el código del frontend
    COPY . .
    
    # Construir la aplicación con Vite
    RUN npm run build
    
    # ---- Etapa 2: Servidor Nginx ----
    FROM nginx:alpine
    
    # Copiar configuración de Nginx (si es necesario)
    COPY nginx.conf /etc/nginx/conf.d/default.conf

    
    # Copiar los archivos construidos al servidor Nginx
    COPY --from=builder /app/dist /usr/share/nginx/html
    
    
    EXPOSE 5173
    
    CMD ["nginx", "-g", "daemon off;"]
    