version: '3.8'

services:
  
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Des_tenpo..2025
      - POSTGRES_DB=Des_tenpo

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/Des_tenpo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Des_tenpo..2025
   

  frontend:
    build:
      context: ./frontent-tenpo
      dockerfile: ../Dockerfile-frontend
    # depends_on:
    #   - backend
    restart: always
    ports:
      - "5173:5173"
    
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
